### PR TITLE
Add "contestants" service

### PR DESCRIPTION
**Pull request by kangkyu**
- Use docker container for the golang service and its postgresql instance
- Currently only showing dummy data (seed and run 😅 ) in the database

### CODE REVIEW

**Comment by a-poor** [comment]
Nice!

That's pretty intense to use Postgres for this! haha 

Are you sure you don't want to use SQLite (e.g. [mattn/go-sqlite3](https://pkg.go.dev/github.com/mattn/go-sqlite3) or [modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite))?

**Comment by a-poor** [comment]
Is the plan to use [HTMX](https://htmx.org/) and [Go Templates](https://pkg.go.dev/html/template)?

**Comment by kangkyu** [comment]
> Is the plan to use [HTMX](https://htmx.org/) and [Go Templates](https://pkg.go.dev/html/template)?

Yes that's the plan we talked about. Yes.

**Comment by kangkyu** [comment]
Closing because we have #2

**Pull request closed without merging**
